### ISSUE TITLE
Default app config not always sticking

### ISSUE THREAD

**Issue by matstocks** [matstocks/PC-Build-Script#1]
The default app settings applied do not always seem to stick. Windows sometimes resets these.

**Comment by kaboddy** [comment]
Windows and other programs tend to do that with updates... May have to look at your AD GPOs to push app defaults regularly.

EDIT:  Oh, you're the dev!  I'm diggin your script.  Is there more of a how too for customizing? :)

**Comment by matstocks** [comment]
> Windows and other programs tend to do that with updates... May have to look at your AD GPOs to push app defaults regularly.
> 
> 
> 
> EDIT:  Oh, you're the dev!  I'm diggin your script.  Is there more of a how too for customizing? :)


You may have a point about updates causing this. We are having this issue on non domain joined systems, so need to try and make it more sticky!

Regarding the how-to I'll make some updates to the readme to make it more detailed.

**Comment by kaboddy** [comment]
> > Windows and other programs tend to do that with updates... May have to look at your AD GPOs to push app defaults regularly.
> > EDIT:  Oh, you're the dev!  I'm diggin your script.  Is there more of a how too for customizing? :)
> 
> You may have a point about updates causing this. We are having this issue on non domain joined systems, so need to try and make it more sticky!
> 
> Regarding the how-to I'll make some updates to the readme to make it more detailed.

Non-domain eh?  Maybe you could schedule something in the Task Scheduler to run and check on login / boot?  👍
